version: "3.7"
services:
  gameshelf:
    image: public.ecr.aws/alexchesters/gameshelf:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gameshelf
    restart: unless-stopped
    volumes:
      - gameshelf_static:/var/www/gameshelf/static
    environment:
      SECRET_KEY: $SECRET_KEY
  nginx:
    image: arm64v8/nginx:1.25.2-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - gameshelf_static:/var/www/gameshelf/static
    ports:
      - 8080:80

volumes:
  gameshelf_static:
