version: "3.7"
services:
  gameshelf:
    image: public.ecr.aws/alexchesters/gameshelf:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gameshelf
    restart: unless-stopped
    volumes:
      - gameshelf_static:/var/www/gameshelf/static
      - gameshelf_db:/usr/lib/gameshelf/db.sqlite3
    environment:
      SECRET_KEY: $SECRET_KEY
      DEBUG_MODE: $DEBUG_MODE
      ALLOWED_HOSTS: pi-apps.chicken-stork.ts.net
      ALLOWED_ORIGINS: https://pi-apps.chicken-stork.ts.net:10014
  nginx:
    image: arm64v8/nginx:1.25.2-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - gameshelf_static:/var/www/gameshelf/static
    ports:
      - 8050:80

volumes:
  gameshelf_static:
  gameshelf_db:
