version: "3.7"
services:
  gameshelf:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gameshelf
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      SECRET_KEY: $SECRET_KEY
