env:
	poetry install

shell:
	poetry shell

server:
	poetry run python manage.py runserver

test:
	poetry run pylint gameshelf

migrations:
	poetry run python manage.py makemigrations

migrate:
	poetry run python manage.py migrate
