# Generated by Django 4.2.4 on 2023-08-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, unique=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("steam", "Steam"),
                            ("epic", "Epic"),
                            ("xbox_pc", "Xbox (PC)"),
                            ("gog_galaxy", "GOG Galaxy"),
                            ("xbox_og", "Xbox (original)"),
                            ("xbox_360", "Xbox 360"),
                            ("xbox_one", "Xbox One"),
                            ("xbox_one_s", "Xbox One S"),
                            ("xbox_series_s", "Xbox Series S"),
                            ("xbox_series_x", "Xbox Series X"),
                            ("ps", "PlayStation"),
                            ("ps2", "PlayStation 2"),
                            ("ps3", "PlayStation 3"),
                            ("ps4", "PlayStation 4"),
                            ("ps5", "PlayStation 5"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
