# Generated by Django 4.2.4 on 2023-08-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "title",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
