# Generated by Django 4.2.4 on 2023-08-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelf", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="status",
            field=models.CharField(
                choices=[
                    ("unplayed", "Unplayed"),
                    ("playing", "Currently playing"),
                    ("completed", "Completed"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
