# Generated by Django 4.2.4 on 2023-08-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelf", "0002_game_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (1, "&#9734;"),
                    (2, "&#9734;&#9734;"),
                    (3, "&#9734;&#9734;&#9734;"),
                    (4, "&#9734;&#9734;&#9734;&#9734;&#9734;"),
                    (5, "&#9734;&#9734;&#9734;&#9734;&#9734;&#9734;"),
                ],
                null=True,
            ),
        ),
    ]
