# Generated by Django 4.2.4 on 2023-08-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelf", "0003_game_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="rating",
            field=models.IntegerField(
                choices=[(1, "☆"), (2, "☆☆"), (3, "☆☆☆"), (4, "☆☆☆☆"), (5, "☆☆☆☆☆")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
