# Generated by Django 4.2.4 on 2023-08-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelf", "0005_alter_game_platform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (0, " "),
                    (1, "☆"),
                    (2, "☆☆"),
                    (3, "☆☆☆"),
                    (4, "☆☆☆☆"),
                    (5, "☆☆☆☆☆"),
                ],
                null=True,
            ),
        ),
    ]
