# Generated by Django 4.2.4 on 2023-08-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelf", "0008_alter_game_options_game_release_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="release_date",
            field=models.DateField(null=True),
        ),
    ]
