# Generated by Django 4.2.4 on 2023-09-02 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shelf", "0011_alter_game_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="game",
            options={"ordering": ["title"]},
        ),
        migrations.RemoveField(
            model_name="game",
            name="ranking",
        ),
    ]
