# Generated by Django 4.2.4 on 2023-10-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelf", "0013_alter_game_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting_to_play", "Waiting to play"),
                    ("playing", "Currently playing"),
                    ("completed", "Completed"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
