# Generated by Django 4.2.4 on 2023-10-18 12:07

from django.db import migrations, models

def rename_old_choices(apps, _schema_editor):
    Game = apps.get_model("shelf", "Game")
    for game in Game.objects.all():
        if game.status in ["wishlist", "unplayed"]:
            game.status = "waiting_to_play"
            game.save()

class Migration(migrations.Migration):

    dependencies = [
        ("shelf", "0013_alter_game_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting_to_play", "Waiting to play"),
                    ("playing", "Currently playing"),
                    ("completed", "Completed"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.RunPython(rename_old_choices)
    ]
