# Generated by Django 4.2.4 on 2023-08-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelf", "0001_initial"),
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shelfuser",
            name="games",
            field=models.ManyToManyField(to="shelf.game"),
        ),
    ]
