# Generated by Django 4.2.4 on 2023-08-25 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shelf", "0001_initial"),
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shelfuser",
            name="games",
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("games", models.ManyToManyField(to="shelf.game")),
            ],
        ),
        migrations.AddField(
            model_name="shelfuser",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="user_profile.collection",
            ),
            preserve_default=False,
        ),
    ]
