# Generated by Django 4.2.4 on 2023-08-25 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shelf", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user_profile", "0002_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShelfUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("games", models.ManyToManyField(to="shelf.game")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
