# Generated by Django 4.2.4 on 2023-08-25 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0002_remove_shelfuser_games_collection_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shelfuser",
            name="collection",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_profile.collection",
            ),
        ),
    ]
